language: java

cache:
 directories:
   - $HOME/.m2

matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8 # JDK 9+175 or newer

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/KinanCity-core/target/KinanCity-core-*.zip"
    - "$TRAVIS_BUILD_DIR/KinanCity-mail/target/KinanCity-mail-*.zip"
    - "$TRAVIS_BUILD_DIR/KinanCity-captcha-server/target/KinanCity-captcha-server-*-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
