language: java

cache:
 directories:
   - $HOME/.m2

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

os:
  - linux

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/KinanCity-core/target/KinanCity-core-*.zip"
  skip_cleanup: true
  on:
    tags: true
