# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Develop Maven Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: Kinan Core
        path: KinanCity-core/target/KinanCity-core*.jar
    - uses: actions/upload-artifact@v2
      with:
        name: Kinan Mail
        path: KinanCity-mail/target/KinanCity-mail*.jar
    - uses: actions/upload-artifact@v2
      with:
        name: Kinan Local Captcha
        path: KinanCity-captcha-server/target/KinanCity-captcha-server*.jar
